name: Prod
on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build Docker image
        run:  docker build -t ${{ secrets.DOCKER_IMAGE }} .


      - name: Push Docker Image
        run: |
          docker login -u=${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }} swr.cn-north-4.myhuaweicloud.com
          docker push ${{ secrets.DOCKER_IMAGE }}
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker And Run Container With SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            echo "login docker repository"
            docker login -u=${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }} swr.cn-north-4.myhuaweicloud.com
            echo "pull docker image"
            docker pull ${{ secrets.DOCKER_IMAGE }}:latest
            echo "stop and remove docker old container"
            docker container stop ${{ secrets.DOCKER_CONTAINER }}
            docker container rm ${{ secrets.DOCKER_CONTAINER }}
            echo "run new docker container"
            docker run -d --net dingtalk-net --name ${{ secrets.DOCKER_CONTAINER }}  -e PROFILES="prod" ${{ secrets.DOCKER_IMAGE }}
            docker image prune -f
