name: Prod
on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker And Run Container With SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/dingtalk-springboot/
            git pull origin master
            mvn package
            docker build -t dingtalk_springboot .
            docker container stop dingtalk_springboot
            docker container rm dingtalk_springboot
            docker run -d --net dingtalk-net --name dingtalk_springboot -v /etc/timezone:/etc/timezone -v /etc/localtime:/etc/localtime -e PROFILES="prod" dingtalk_springboot
            docker image prune -f
            
