name: Test Environment
on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Cache maven
      uses: actions/cache@v2
      id: cache
      with:
        path: ~/.m2/repository
        key: maven-${{ hashFiles('**/pom.xml') }}

    - name: Build with Maven
      if: steps.cache.outputs.cache-hit != 'true'
      run: mvn -B package --file pom.xml

    - name: Build Docker image
      run:  docker build -t ${{ secrets.DOCKER_IMAGE }} .


    - name: Push Docker Image
      run: |
        docker login -u=${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }} swr.cn-north-4.myhuaweicloud.com
        docker push ${{ secrets.DOCKER_IMAGE }}

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Pull Docker And Run Container With SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.TEST_HOST }}
        username: ${{ secrets.TEST_USER }}
        key: ${{ secrets.TEST_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          echo "login docker repository"
          docker login -u=${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }} swr.cn-north-4.myhuaweicloud.com

          echo "pull docker image"
          docker pull ${{ secrets.DOCKER_IMAGE }}:latest

          echo "stop and remove docker old container"
          docker container stop ${{ secrets.DOCKER_CONTAINER }}
          docker container rm ${{ secrets.DOCKER_CONTAINER }}

          echo "run new docker container"
          docker run -d --net dingtalk-net --name ${{ secrets.DOCKER_CONTAINER }}  -e PROFILES="test" ${{ secrets.DOCKER_IMAGE }}
          docker image prune -f
